language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - gh-pages

install:
  - yarn install
  - yarn run generate

script:
  - echo "Skipping tests"

root:
  dist: xenial
  os: linux

deploy:
  strategy: git
  provider: pages
  cleanup: true
  token: $GITHUB_ACCESS_TOKEN
  target_branch: master
  local_dir: dist
  on:
    branch: gh-pages