language: node_js
node_js:
  - "10"

cache:
  directories:
    - "node_modules"

branches:
  only:
  - gh-pages

install:
  - yarn install
  - DEPLOY_ENV=MASTER yarn run generate

script:
  - echo "Skipping tests"

root:
  dist: xenial
  os: linux

deploy:
  strategy: git
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_ACCESS_TOKEN
  target-branch: master
  local-ir: dist
  on:
    branch: gh-pages